{% set version = '1.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidygraph
  version: {{ version|replace("-", "_") }}

source:
  fn: tidygraph_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/tidygraph_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidygraph/tidygraph_{{ version }}.tar.gz
  sha256: 6419cfdfb7a160e8f032c62cd68ab12dbd870994a53a182443baa878438c15b3

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
  host:
    - r-base
    - r-r6
    - r-rcpp
    - r-dplyr >=0.7
    - r-igraph
    - r-magrittr
    - r-rlang
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-r6
    - r-rcpp
    - r-dplyr >=0.7
    - r-igraph
    - r-magrittr
    - r-rlang
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('tidygraph')"           # [not win]
    - "\"%R%\" -e \"library('tidygraph')\""  # [win]

about:
  home: https://github.com/thomasp85/tidygraph
  license: MIT
  summary: A graph, while not "tidy" in itself, can be thought of as two tidy data frames describing
    node and edge data respectively. 'tidygraph' provides an approach to manipulate
    these two virtual data frames using the API defined in the 'dplyr' package, as well
    as provides tidy interfaces to  a lot of common graph algorithms.
  license_family: MIT

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
