travis:
  secure:
    BINSTAR_TOKEN: E18gb+vBt1jaoJ9ZM7j0ZKIZMlCgjAX/rWjWipKTfsZLXYh1q5L1lrNif/9TJ7eD+YVlPMzXmVEwyWcR2fgbFB+2bVuphycSAJC0Dd67uv8b247cSEDi38T/0xelhvd7yKQR8jbnk+hIJSH5dlNQzTcUFfvmNEPAT/S51XvbLlwX2ecuF8z9aMs+s5tkOJTZCU8SlKe6k1ESbXrEh9l2FCgH03n5CYed1Kq4P3+0b+AR64gdK7Ur601umN3cu6GjWyeRfDeBdXL18NGYlyPzDjpYrKvEroWRGMzOsCp8hxHC1PS2WWdKZsaz4BMIoKASW5L8FWe+ugM/e3R8pEzz6DMoLqj3Rltu8s3wCegMFhCR98XMkFzyQGbPFdRlksJQ0/wm2boDKT0V2lG122J4qRylPcUBprfHeyWOlWPJ+5GMjO7L6VzH/COB6Godved9M1r7FAuhVlNxZm+Xfc4xFcjE+wE94EgkpXOv5tP+a8au16c/YnDF50yg3F8UMdgVzaPwmTczeXDs+WW2gnd8fHUS0yVe7/7DTWW8naLfbiN/JskM4k4tJ2drLAY48l4PQyTGR8AYElz/LerrNjmSZ2Fy73KXPCVge4Bi2XycfAR+mYCKIG7D9SgxnA3v2RrsWr1xGL70KhVbZ/qt6MmvSwcTe2Nt6yQOgYcHC0OGdcg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
